In [1]:
# Data handling
import numpy as np
import pandas as pd

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [3]:
data = pd.read_csv("Students Performance Dataset.csv")
data.head()

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,...,Projects_Score,Total_Score,Grade,Study_Hours_per_Week,Extracurricular_Activities,Internet_Access_at_Home,Parent_Education_Level,Family_Income_Level,Stress_Level (1-10),Sleep_Hours_per_Night
0,S1000,Omar,Williams,student0@university.com,Female,22,Mathematics,97.36,40.61,59.61,...,62.84,59.8865,F,10.3,Yes,No,Master's,Medium,1,5.9
1,S1001,Maria,Brown,student1@university.com,Male,18,Business,97.71,57.27,74.00,...,98.23,81.9170,B,27.1,No,No,High School,Low,4,4.3
2,S1002,Ahmed,Jones,student2@university.com,Male,24,Engineering,99.52,41.84,63.85,...,91.22,67.7170,D,12.4,Yes,No,High School,Low,9,6.1
3,S1003,Omar,Williams,student3@university.com,Female,24,Engineering,90.38,45.65,44.44,...,55.48,51.6535,F,25.5,No,Yes,High School,Low,8,4.9
4,S1004,John,Smith,student4@university.com,Female,23,CS,59.41,53.13,61.77,...,87.43,71.4030,C,13.3,Yes,No,Master's,Medium,6,4.5

In [4]:
data[data.isnull().any(axis=1)]

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,...,Projects_Score,Total_Score,Grade,Study_Hours_per_Week,Extracurricular_Activities,Internet_Access_at_Home,Parent_Education_Level,Family_Income_Level,Stress_Level (1-10),Sleep_Hours_per_Night
5,S1005,Liam,Brown,student5@university.com,Male,21,Mathematics,60.60,70.21,64.48,...,67.65,68.0900,D,25.3,Yes,No,NaN,Medium,6,5.6
7,S1007,Ahmed,Smith,student7@university.com,Male,19,Engineering,65.91,91.72,59.47,...,90.04,71.3685,C,16.7,Yes,Yes,NaN,Low,5,7.8
9,S1009,Sara,Smith,student9@university.com,Female,22,Business,89.45,95.69,86.97,...,83.09,82.7555,B,9.4,Yes,No,NaN,High,8,7.1
11,S1011,Omar,Williams,student11@university.com,Female,20,Mathematics,59.30,93.34,87.90,...,66.17,77.6705,C,22.9,Yes,No,NaN,Low,7,8.6
12,S1012,John,Davis,student12@university.com,Male,21,Engineering,95.48,67.24,97.23,...,54.02,70.9090,C,26.2,No,No,NaN,Medium,9,6.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4977,S5977,Omar,Johnson,student4977@university.com,Male,21,Engineering,92.35,58.06,41.34,...,77.40,62.4540,D,25.9,No,No,NaN,Low,4,8.2
4981,S5981,John,Davis,student4981@university.com,Male,22,Business,69.28,97.83,72.67,...,63.95,71.5645,C,25.1,No,Yes,NaN,Low,7,7.8
4984,S5984,Liam,Johnson,student4984@university.com,Female,20,Mathematics,98.35,45.14,86.63,...,91.45,83.4425,B,8.4,Yes,Yes,NaN,Medium,9,4.5
4996,S5996,Emma,Brown,student4996@university.com,Male,19,Mathematics,96.30,78.67,47.42,...,52.33,59.0240,F,24.2,No,Yes,NaN,Medium,4,7.2
4997,S5997,John,Brown,student4997@university.com,Female,24,CS,89.94,50.84,65.83,...,97.89,74.7560,C,7.6,No,Yes,NaN,High,5,6.6

In [5]:
data

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,...,Projects_Score,Total_Score,Grade,Study_Hours_per_Week,Extracurricular_Activities,Internet_Access_at_Home,Parent_Education_Level,Family_Income_Level,Stress_Level (1-10),Sleep_Hours_per_Night
0,S1000,Omar,Williams,student0@university.com,Female,22,Mathematics,97.36,40.61,59.61,...,62.84,59.8865,F,10.3,Yes,No,Master's,Medium,1,5.9
1,S1001,Maria,Brown,student1@university.com,Male,18,Business,97.71,57.27,74.00,...,98.23,81.9170,B,27.1,No,No,High School,Low,4,4.3
2,S1002,Ahmed,Jones,student2@university.com,Male,24,Engineering,99.52,41.84,63.85,...,91.22,67.7170,D,12.4,Yes,No,High School,Low,9,6.1
3,S1003,Omar,Williams,student3@university.com,Female,24,Engineering,90.38,45.65,44.44,...,55.48,51.6535,F,25.5,No,Yes,High School,Low,8,4.9
4,S1004,John,Smith,student4@university.com,Female,23,CS,59.41,53.13,61.77,...,87.43,71.4030,C,13.3,Yes,No,Master's,Medium,6,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,S5995,Ahmed,Jones,student4995@university.com,Male,19,CS,96.09,45.86,45.63,...,51.66,53.5470,F,7.8,No,No,Master's,Medium,10,4.5
4996,S5996,Emma,Brown,student4996@university.com,Male,19,Mathematics,96.30,78.67,47.42,...,52.33,59.0240,F,24.2,No,Yes,NaN,Medium,4,7.2
4997,S5997,John,Brown,student4997@university.com,Female,24,CS,89.94,50.84,65.83,...,97.89,74.7560,C,7.6,No,Yes,NaN,High,5,6.6
4998,S5998,Sara,Davis,student4998@university.com,Male,23,Engineering,99.09,55.44,57.45,...,84.74,68.6585,D,14.5,Yes,No,PhD,Medium,10,5.9
4999,S5999,Maria,Brown,student4999@university.com,Female,21,Mathematics,90.33,93.29,88.42,...,66.23,78.7485,C,29.9,Yes,Yes,PhD,High,2,5.3

In [8]:
data_trimmed = data[['Student_ID', 'First_Name', 'Last_Name', 'Attendance (%)', 'Midterm_Score', 'Final_Score', 'Assignments_Avg', 'Quizzes_Avg', 'Participation_Score', 'Projects_Score', 'Total_Score', 'Grade', 'Study_Hours_per_Week', 'Extracurricular_Activities','Stress_Level (1-10)', 'Sleep_Hours_per_Night' ]]

In [9]:
data_trimmed

,Student_ID,First_Name,Last_Name,Attendance (%),Midterm_Score,Final_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Total_Score,Grade,Study_Hours_per_Week,Extracurricular_Activities,Stress_Level (1-10),Sleep_Hours_per_Night
0,S1000,Omar,Williams,97.36,40.61,59.61,73.69,53.17,73.4,62.84,59.8865,F,10.3,Yes,1,5.9
1,S1001,Maria,Brown,97.71,57.27,74.00,74.23,98.23,88.0,98.23,81.9170,B,27.1,No,4,4.3
2,S1002,Ahmed,Jones,99.52,41.84,63.85,85.85,50.00,4.7,91.22,67.7170,D,12.4,Yes,9,6.1
3,S1003,Omar,Williams,90.38,45.65,44.44,68.10,66.27,4.2,55.48,51.6535,F,25.5,No,8,4.9
4,S1004,John,Smith,59.41,53.13,61.77,67.66,83.98,64.3,87.43,71.4030,C,13.3,Yes,6,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,S5995,Ahmed,Jones,96.09,45.86,45.63,74.13,81.53,9.8,51.66,53.5470,F,7.8,No,10,4.5
4996,S5996,Emma,Brown,96.30,78.67,47.42,57.89,85.96,47.8,52.33,59.0240,F,24.2,No,4,7.2
4997,S5997,John,Brown,89.94,50.84,65.83,84.69,82.27,7.5,97.89,74.7560,C,7.6,No,5,6.6
4998,S5998,Sara,Davis,99.09,55.44,57.45,78.78,55.96,62.9,84.74,68.6585,D,14.5,Yes,10,5.9
4999,S5999,Maria,Brown,90.33,93.29,88.42,87.06,65.22,64.0,66.23,78.7485,C,29.9,Yes,2,5.3

In [12]:
data_trimmed[data_trimmed.isnull().any(axis=1)]

Empty DataFrame
Columns: [Student_ID, First_Name, Last_Name, Attendance (%), Midterm_Score, Final_Score, Assignments_Avg, Quizzes_Avg, Participation_Score, Projects_Score, Total_Score, Grade, Study_Hours_per_Week, Extracurricular_Activities, Stress_Level (1-10), Sleep_Hours_per_Night]
Index: []